Ecommerce/Ecommerce/Models/ErrorViewModel.cs
using System;

namespace Ecommerce.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ecommerce/Ecommerce/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Ecommerce.Core.IServices;
using Ecommerce.Domain.Models;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
namespace Ecommerce.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserServices _userServices;
        public AuthController(IUserServices userServices)
        {
            _userServices = userServices;
        }
        public IActionResult Login()
        {
            UserLoginDetails userDetails = new UserLoginDetails(HttpContext.Session.GetString("userEmail"), HttpContext.Session.GetString("userPass"));
            return View(userDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserLoginDetails user)
        {
            if(ModelState.IsValid)
            {
                var userId = await _userServices.LoginAsync(user);
                if (userId != "NOT_FOUND")
                {
                    HttpContext.Session.SetString("userId", userId);
                    HttpContext.Session.SetString("userEmail", user.Email);
                    return RedirectToAction("Index", "Home");
                }
            }
            ModelState.AddModelError("Email", "this record  doesnt exist in the data base");
            return View(user);
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(UserRegistration user)
        {
            if(user.RetypePassword != user.Password)
            {
                ModelState.AddModelError("RetypePassword", "the Password those not match");
            }
            if (ModelState.IsValid)
            {
                var userInfo = await _userServices.RegisterUserAsync(user);
                if (userInfo != null)
                {
                    HttpContext.Session.SetString("userId", userInfo.UserId);
                    HttpContext.Session.SetString("userEmail", userInfo.Email);
                    HttpContext.Session.SetString("userPass", user.Password);
                    return RedirectToAction("Login");
                }
                else
                {
                    ModelState.AddModelError("Email", "this email already exist");
                    return View(user);
                }
            }
            return View(user);
        }
    }
}

Ecommerce/Ecommerce/Controllers/DetailsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Ecommerce.Core.ViewModel;
using Ecommerce.Core.IServices;
using System.Threading.Tasks;

namespace Ecommerce.Controllers
{
    public class DetailsController : Controller
    {
        private readonly IProductServices _productServices; 
        public DetailsController(IProductServices productServices)
        {
            _productServices = productServices; 
        }
        public async Task<IActionResult> Index(string ? id)
        {
            if (HttpContext.Session.GetString("userId") != null)
            {
                var productDetails = await _productServices.GetProductByIdAsync(id);
                HomeProductViewModel ViewData = new HomeProductViewModel();
                ViewData.Product = productDetails;
                ViewData.SessionId = HttpContext.Session.GetString("userId");
                ViewData.Email = HttpContext.Session.GetString("userEmail");
                ViewData.FirstSixBestSales = await _productServices.FirstSixBestSalesAsync();
                return View(ViewData);
            }
            return RedirectToAction("Login","Auth");
        }
    }
}

Ecommerce/Ecommerce/Controllers/HomeController.cs
using Ecommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;
using System.Threading.Tasks;
using Ecommerce.Core.IServices;
using Ecommerce.Core.ViewModel;
namespace Ecommerce.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductServices _productServices;
        public HomeController(ILogger<HomeController> logger, IProductServices productServices)
        {
            _productServices = productServices;
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            var homeViewModel = new HomeProductViewModel(
                                await _productServices.FirstThreeBestSalesAsync(),
                                await _productServices.FirstSixBestSalesAsync(), 
                                await _productServices.NewSalesAsync(),
                                HttpContext.Session.GetString("userId"),
                                HttpContext.Session.GetString("userEmail")); 
            return View(homeViewModel);
        }
        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ecommerce/Ecommerce/Views/Details/Index.cshtml
@model HomeProductViewModel;

@{
	ViewData["Title"] = "Details Page";
	ViewBag.DiscountPrice = (Model.Product.Price * ((decimal)Model.Product.Discount/100)).ToString("0.00");
}
<style>
	#detailsSideview div:nth-child(1),
	#detailsSideview div:nth-child(2) div{
		background-repeat: no-repeat;
		background-size: cover;
		background-position: center;
	}

	#detailsSideview div:nth-child(2) div {
		border:solid lightgrey 2px;
		margin:0 1px;
		height:90px;
	}
</style>


<div class="Cont" style="background-color: ghostwhite;margin-left:-8px; height:40px;justify-content:center;align-items:center">
	<span> <span style="color:dodgerblue">Home</span> / <span style="color:dodgerblue">Hot Deal</span> / <span>@Model.Product.Name</span></span>
</div>

<div class="Cont" style=" margin-top:30px">
	<div class="center">
		<div style="width:80%;display:flex; flex-direction:column">
			<div style="display:flex;flex-direction:row">
				<div id="detailsSideview" style="flex-grow:6;display:flex;flex-direction:column">
					<div style="background-image:url('@Model.Product.Url');height:300px;
					border-radius: 10px;"></div>
					<div style="display:flex;flex-direction:row; margin-top:30px">
						<div style="flex-grow:1; background-image:url('@Model.Product.Url')">
						</div>
						<div style="flex-grow:1;background-image:url('@Model.Product.Url')">
						</div>
						<div style="flex-grow:1;background-image:url('@Model.Product.Url')">
						</div>
						<div style="flex-grow:1;background-image:url('@Model.Product.Url')">
						</div>
					</div>
				</div>

				<div style="flex-grow:1; padding-left:40px">
					<h2>@Model.Product.Name</h2>	
					<div style="display:flex">
						<div style="margin-right:20px">
							<partial name="_ShowStarRatings" model="@Model.Product.Rating"/>
						</div>
						<span style="color:lightgrey;margin-right:20px">0 reviews</span>
						<span style="color:dodgerblue;margin-right:20px">Submit a review</span>
					</div>
					<hr style="border:thin ghostwhite 0.2px" />
					<div style="display:inline-flex;margin:15px 0px">
						<span style="color:dodgerblue;font-weight:900;margin-right:10px">$@ViewBag.DiscountPrice</span>
						<span style="color:lightgrey;text-decoration:line-through;margin-right:10px">$@Model.Product.Price</span>
						<span style="color:coral;margin-right:10px">@Model.Product.Discount% off</span>
					</div>
					<div style="display:flex;flex-direction:row;font-size:80%">
						<div style="display:flex;flex-direction:column">
							<span style="margin-bottom:15px">
								Availability: 
							</span>
							<span style="margin-bottom:15px">Category: </span>
							<span style="margin-bottom:15px">Free Shipping:
								@if	(Model.Product.Shipping)
								{
									<span>Yes</span>
								}else{
									<span>No</span>
								}

							</span>
						</div>
						<div style="display:flex;flex-direction:column">
							<span style="margin-bottom:15px">@Model.Product.Availability</span>
							<span style="margin-bottom:15px">@Model.Product.Category</span>
						</div>
					</div>
					<hr style="border:thin ghostwhite 0.2px" />
					<div>
						<div style="display:flex">
							<span style="margin-right:60px;font-size:80%;font-weight:700">Select Color:</span>
							<div style="margin-left:15px;height:20px;width:20px;border-radius:100px;background-color:dodgerblue"></div>
							<div style="margin-left:15px;height:20px;width:20px;border-radius:100px;background-color:red"></div>
							<div style="margin-left:15px;height:20px;width:20px;border-radius:100px;background-color:black"></div>
							<div style="margin-left:15px;height:20px;width:20px;border-radius:100px;background-color:yellow"></div>
						</div>
						<div style="display:inline-flex;margin-top:10px">
							<span style="font-size:80%;font-weight:700;margin-right:120px">Size</span>
							<select style="outline:none;width:100px;padding:5px 20px">
								<option Selected>XS</option>
								<option>S</option>
								<option>M</option>
								<option>L</option>
							</select>
						</div>
					</div>
					<hr style="border:thin ghostwhite 0.2px" />
					<div style="display:flex;justify-content:space-between">
						<div style="display:inline-flex;background-color:ghostwhite;padding:10px 20px">
							<span style="color:dodgerblue">-</span>
							<span style="margin:0 20px">0</span>
							<span style="color:dodgerblue">+</span>
						</div>
						<button style="background-color:aquamarine;padding:10px 20px;color:white;border:none;border-radius:5px">
							<span class="fa fa-cart-shopping"></span>
							<span>Add To Cart</span>
						</button>
					</div>
					<hr style="border:thin ghostwhite 0.2px" />
					<div style="display:flex;margin:30px 0px 70px 0px;cursor:pointer">
						<button style="outline:none;border:none;color:white;font-weight:600;flex-grow:1;border-radius:3px; margin-right:5px;padding:20px 30px; background-color:cornflowerblue"><span class="fa fa-facebook"></span>share on facebook</button>
						<button style="outline:none;border:none;color:white;font-weight:600; flex-grow:1;border-radius:3px; margin-left:5px;padding:20px 30px; background-color:dodgerblue"><span class="fa fa-twitter"></span>share on twitter</button>
					</div>
				</div>
			</div>

			<div style="background-color:ghostwhite;padding:10px;border-radius:7px;margin-bottom:50px">
				<h2>Product Information</h2>
				<hr style="border:thin ghostwhite 0.2px" />
				<div style="color:gray">
					<p style="overflow-wrap:break-word">
						@Model.Product.Description
					</p>
					
					<p style="overflow-wrap:break-word">
						@Model.Product.Description
					</p>

					<p >
						@Model.Product.Description
					</p>
				</div>
			</div>
		</div>


		<div style="width:20%;flex-grow:6!important;display:flex;padding-left:30px">
			<div>
				<h3 style="color:lightgrey">BEST SELLER</h3>
				<div style="background-image:url('@Model.FirstSixBestSales[2].Url');background-size:contain;
				height:300px;background-repeat:no-repeat;display:flex;align-items:flex-end">
					<div style="display:flex;flex-direction:column;justify-content:center">
						<h4 style="align-self:center" >@Model.FirstSixBestSales[2].Name</h4>
						<div style="display:flex;justify-content:center">
							<partial name="_ShowStarRatings" model="@Model.FirstSixBestSales[2].Rating" />
						</div>
						<div style="justify-content:center">
							<span style="color:dodgerblue;font-weight:900;margin-right:5px">$299,43</span>
							<span style="color:lightgrey;text-decoration:line-through;margin-right:5px">$534,33</span>
							<span style="color:coral;margin-right:5px">24% off</span>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>



</div>

<div class="Cont">
	<h1>
		RELATED PRODUCTS
	</h1>
</div>

<!-- the majoe show case-->
<div class="Cont">
	<div class="center" style="flex-wrap:wrap">
		@for(var item = 0; item < 4; item++){
			<partial name="_FeaturedProductPartial" model="Model.FirstSixBestSales[item]" />
		}
	</div>
</div>

Ecommerce/Ecommerce/Views/Home/Index.cshtml
@model HomeProductViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="Cont ImageShow" >
	<div class="center">
		<h1>Super Flash Sale <br> 50% Off</h1>
	</div>
</div>

<div class="Cont Show">
	<div class="center">
		@foreach(var item in Model.FirstThreeBestSales)
		{
			<a asp-action="index" asp-controller="Details" asp-route-id="@item.Id" style="background-image:url(@item.Url);text-decoration:none" class="ShowItem">
				<h3>@item.Name</h3>
				<span>$@item.PriceDiscount.ToString("0.00")</span>
				<p><i >$@item.Price</i><b>@item.Discount% off</b></p>
			</a>

		}
	</div>
</div>

<div class="Cont" style="margin-top:300px!important">
	<h1>
		BEST SELLER
	</h1>
</div>

<div class="Cont">
	<div class="center" style="justify-Content;width:45%;font-size:23px">
		<span style="color:#0099ff;text-decoration:underline">All</span>
		<span>Bags</span>
		<span>Sneakers</span>
		<span>Belt</span>
		<span>Sunglasses</span>
	</div>
</div>

<!-- the majoe show case-->
<div class="Cont">
	<div class="center" style="flex-wrap:wrap">
		@foreach(var item in Model.FirstSixBestSales){
			<partial name="_FeaturedProductPartial" model="item" />
		}
		</div>
	</div>
</div>

<div class="Cont">
	<h3 style="text-decoration:underline;color:#336699; cursor:pointer" >LOAD MORE</h3>
</div>

<div class="Cont banner" style="margin-bottom:70px;">
	<div class="center" style="color:white">
		<div style="flex-grow:1;align-self:center">
			<h1 style="font-size:50px">Addidas Men Running <br>Sneakers </h1>
			<h4>Performance and design taken right to the edge</h4>
			<div style="font-weight:700">
				<span style="text-decoration: underline;">SHOP N</span><span>OW</span>
			</div>
		</div>
		<div style="flex-grow:1;align-self:center;position:relative">
			<img src="~/Images/bannerShoe.png" style="position:absolute;top:-320px;right:0px" width="710px" height="auto" alt="" />
		</div>
	</div>
</div>

<div class="Cont CustomerCare">
	<div class="center">
		<div>
			<span class="fa fa-shipping-fast"></span>
			<h2>FREE SHIPPING</h2>
			<div>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</div>
		</div>
		<div>
			<span class="fa fa-dollar-sign"></span>
			<h2>100% REFUND</h2>
			<div>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</div>
		</div>
		<div>
			<span class="fa fa-teamspeak"></span>
			<h2>SUPPORT 24/7</h2>
			<div>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</div>
		</div>
	</div>
</div>

<div class="Cont" style="margin-top:100px!important;margin-bottom:70px!important">
	<h1>
		LASTEST NEWS
	</h1>
</div>

<div class="Cont News_details">
	<div class="center">
		<div style="display:flex">
			<img src="~/Images/nike.png" alt="" />
			<div>
				<span style="color:gray" class="date">01 Jan, 2015</span>
				<span style="font-size:25px;font-weight:600;display:flex">Fashion Industry</span>
				<div>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</div>
			</div>
		</div>
		<div style="display:flex">
			<img src="~/Images/figma.png" alt="" />
			<div>
				<span style="color:gray" class="date">01 Jan, 2015</span>
				<span style="font-size:25px;font-weight:600;display:flex">Best Design Tools</span>
				<div>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</div>
			</div>
		</div>
		<div style="display:flex">
			<img src="~/Images/kronos.png" alt="" />
			<div>
				<span style="color:gray" class="date">01 Jan, 2015</span>
				<span style="font-size:25px;font-weight:600;display:flex">HR Community</span>
				<div>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</div>
			</div>
		</div>
	</div>
</div>

<div class="Cont" style="margin-top:100px!important;margin-bottom:70px!important">
	<h1>
		FEATURED PRODUCTS
	</h1>
</div>

<div class="Cont Featured_details">
	<div class="center">
		@foreach(var item in Model.NewSales){
			<a asp-action="index" asp-controller="Details" asp-route-id="@item.Id" style="display:flex;text-decoration:none">
				<img src=@item.Url width="200px" height = "auto" alt="" />
				<div>
					<div>
						<h4>@item.Name</h4>
						<div>
							<partial name="_ShowStarRatings" model="item.Rating"/>
						</div>
						<div>
							<span style="color:red">$@item.PriceDiscount</span>
							<span style="text-decoration:line-through;color:grey">$@item.Price</span>
						</div>
					</div>
				</div>
			</a>
		}

		
	</div>
</div>

<div class="Cont Search" style="margin-top:100px!important;margin-bottom:70px!important;display:inline-flex">
	<input type="text" value="" style="border-radius: 5px 0 0 5px ;width:400px;border-color:#40BFFF;border-style:solid;outline:none;padding:10px" placeholder="Search query..." />
	<button style="cursor:pointer;background-color:#40BFFF;color:white;border:none;padding:20px 25px;border-radius:0 5px 5px 0">Search</button>
</div>

Ecommerce/Ecommerce/Views/Shared/_FeaturedProductPartial.cshtml
@model ProductDisplayDTO;

<a asp-action="index" asp-controller="Details" asp-route-id="@Model.Id" style="text-decoration:none" class="storeItem">
	<div style="background-image:url(@Model.Url);">
	</div>
	<div>
		<h4>@Model.Name</h4>
		<div>
			<partial name="_ShowStarRatings" model="Model.Rating"  />
		</div>
		<div>
			<span>$@Model.PriceDiscount</span>
			<span><i>$@Model.Price </i>@Model.Discount% off</span>
		</div>
	</div>
</a>

Ecommerce/Ecommerce/Views/Shared/_Layout.cshtml
@model HomeProductViewModel;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce</title>
    <link rel="stylesheet" href="~/css/GeneralStyle.css">
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css">
</head>
<body>
	<div class="Cont profileHeader" style="padding-top:3px">
		<div class="center" style="font-size:16px">
            <div class="first" style="cursor:pointer;flex-grow:8">
                <span style="margin-right:10px!important">EN<i class="fa fa-caret-down"></i></span>
                <span>USD <i class="fa fa-caret-down"></i></span>
            </div>
            <div class="second" style="cursor:pointer;flex-grow:1;display:flex; justify-content:space-between;align-items:center">
                @if(Model.SessionId == null)
                {
                    <button style="padding:10px 30px;border-radius:4px;border:none;cursor:pointer;background:dodgerblue"><a asp-controller="Auth" asp-action="Register" style="color:white;text-decoration:none;font-weight:600;"><span class="fa fa-user"></span>Register</a></button>
                    <button style="padding:10px 30px;border-radius:4px;border:none;cursor:pointer"><a asp-controller="Auth" asp-action="Login" style="color:dodgerblue;text-decoration:none;font-weight:600;"><span class="fa fa-sign-in"></span>Login in</a></button>
                }
                @if(Model.Email == null){
                    <span><i class="fa fa-user"></i>
                        My Profile
                    </span>
                }else{
                    <a style="text-decoration:none;color:forestgreen" title="logout" asp-controller="Home" asp-action="Logout" >
                        <i class="fa fa-user"></i>
                         @Model.Email
                    </a>
                }
                <span><i class="fa fa-cart-shopping"></i>Items</span>
                <span>$0.00<i class="fa fa-search"></i></span>
            </div>
        </div>
    </div>
    <div class="Cont pageHeader">
        <div class="center" style="height:100px;background;align-items:center;font-weight:300">
            <div style="flex-grow:5;cursor:pointer;display:flex; position:relative">
				<img src="~/Images/Rectangle 383.png" width="35px" height="35px" alt="logo" />
				<img src="~/Images/Vector 40 (Stroke).png" style="position:absolute;left:8px;top:6px" width="20px" height="auto" alt="" />
				<span style="font-size:18px;font-weight:600;margin-left:15px;align-self:center">E-Comm</span>
            </div>
            <div style="font-size:20px;flex-grow:2;display:flex;justify-content:space-between;cursor:pointer">
                <span style="color:dodgerblue">HOME</span>
                <span>BAGS</span>
                <span>SNICKERS</span>
                <span>BELT</span>
                <span>CONTACT</span>
            </div>
        </div>
    </div>
    @RenderBody()
    <div class="Cont Bottom" style="background-color:lightblue;margin-left:-8px">
        <div class="center" style="height:600px;padding-top:70px;flex-wrap:wrap">
            <div style="width:30%">
                <div style="flex-grow:5;cursor:pointer;display:flex; position:relative">
                    <img src="~/Images/Rectangle 383.png" width="35px" height="35px" alt="logo" />
                    <img src="~/Images/Vector 40 (Stroke).png" style="position:absolute;left:8px;top:6px" width="20px" height="auto" alt="" />
                    <span style="font-size:18px;font-weight:600;margin-left:15px;align-self:center">E-Comm</span>
                </div>
                <div style="margin-top:10px!important">
                    Lorem Ipsum is simply dummy text of the <br>
                    printing and typesetting industry. Lorem <br>
                    Ipsum has been the industry's standard <br>
                    dummy text ever.Since the 1500s, when an <br>
                    unknown printer.
                </div>
            </div>

            <div style="width:30%">

                <div style="flex-grow:5;cursor:pointer;display:flex; position:relative">
                    <span style="font-weight:700;font-size:20px">Follow Us</span>
                </div>
                <div style="margin-top:10px!important">
                    Since the 1500s, when an unknown`<br>
                    printer took a galley of type and scrambled.
                    <i class="fa fa-facebook-f"></i>
                    <i class="fa fa-square-twitter"></i>
                </div>

            </div>

            <div style="width:30%">
                <div style="flex-grow:5;cursor:pointer;display:flex; position:relative">
                    <span style="font-weight:700;font-size:20px">Contact Us</span>
                </div>
                <div style="margin-top:10px!important">
                    E-Comm , 4578 <br>Marmora Road,<br> Glasgow D04 89GR
                </div>
            </div>

            <div style="width:20%">
                <div style="flex-grow:5;cursor:pointer;display:flex; position:relative">
                    <span style="font-weight:700;font-size:20px">Information</span>
                </div>
                <div style="margin-top:10px!important">
                    About Us<br>
                    Infomation <br>
                    Privacy Policy <br>
                    Terms & Conditions
                </div>
            </div>

            <div style="width:20%">
                <div style="flex-grow:5;cursor:pointer;display:flex; position:relative">
                    <span style="font-weight:700;font-size:20px">Service</span>
                </div>
                <div style="margin-top:10px!important">
                    About Us<br>
                    Infomation <br>
                    Privacy Policy <br>
                    Terms & Conditions
                </div>
            </div>
            <div style="width:20%">
                <div style="flex-grow:5;cursor:pointer;display:flex; position:relative">
                    <span style="font-weight:700;font-size:20px">My Account</span>
                </div>
                <div style="margin-top:10px!important">
                    About Us<br>
                    Infomation <br>
                    Privacy Policy <br>
                    Terms & Conditions
                </div>
            </div>
            <div style="width:30%">
                <div style="flex-grow:5;cursor:pointer;display:flex; position:relative">
                    <span style="font-weight:700;font-size:20px">Our Offers</span>
                </div>
                <div style="margin-top:10px!important">
                    About Us<br>
                    Infomation <br>
                    Privacy Policy <br>
                    Terms & Conditions
                </div>
            </div>
			
		</div>
    </div>
        
    @RenderSection("Scripts", required: false)
    
</body>
</html>

Ecommerce/Ecommerce/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
	<link rel="stylesheet" href="~/css/Auth.css" />
</head>
<body>
	<div class="cover"></div>
    <div class="container">
		<div class="center">
			<div style="width:70%;display:flex;flex-direction:column;margin-top:20px">
                <div style="cursor:pointer;display:flex;position:relative;justify-content:center;height:40px;align-items:center">
                    <img src="~/Images/Rectangle 383.png" width="35px" height="35px" alt="logo" />
                    <img src="~/Images/Vector 40 (Stroke).png" style="position:absolute;margin-left:-86px;margin-top:0px;" width="20px" height="auto" alt="" />
                    <span style="font-size:18px;font-weight:800; margin-left:10px;font-family:Cooper">E-Comm</span>
                </div>
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

Ecommerce/Ecommerce/Views/Shared/_ShowStarRatings.cshtml
@model Ratings;

@for(int i = 0; i < (int)@Model; i++){
	<img src="~/Images/star copy.png" alt="" />
}
@for (int i = 0; i < 5 - (int)@Model; i++)
{
	<img src="~/Images/starfade.png" alt="" />
}